######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 12 22:25:56 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.moc
SOURCES += main.cpp
